list: $/gemfourmedia/gcover/models/cover/columns.yaml
modelClass: GemFourMedia\GCover\Models\Cover
title: Cover
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'gemfourmedia/gcover/cover/update/:id'
